version: "3.8"

services:
  postgresdb:
    ports:
      - "7000:${DB_PORT}"
    volumes:
      - dev_trancendence_posgresdb:/var/lib/postgresql/data
    # to ensure database is alive before starting every other service
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USER -d $DB_NAME"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    volumes:
      - dev_redis_volume:/data
    ports:
      - "3002:6379"

  nginx:
    volumes:
      - dev_cdn_volume:/var/www/42trancendence/avatar:ro

  nestjs:
    volumes:
      - dev_cdn_volume:/trancendence_nestjs/avatars
      - ./backend:/trancendence_nestjs
      - /trancendence_nestjs/node_modules/
    entrypoint: ["npx", "nest", "start", "--watch"]

  nextjs:
    volumes:
      - ./frontend:/trancendence_nextjs
      - /trancendence_nextjs/node_modules/
      - /trancendence_nextjs/.pnpm-store/
    entrypoint: ["npx", "next", "dev"]

volumes:
  dev_cdn_volume:
  dev_redis_volume:
  dev_trancendence_posgresdb:
