version: "3.8"

services:
  postgresdb:
    container_name: postgresdb
    image: postgres:14.7-alpine3.17
    restart: unless-stopped
    configs:
      - source: postgres_initsql
        target: /docker-entrypoint-initdb.d/init.sh
    networks:
      - ft_trancendence

  redis:
    container_name: redis
    image: redis:7.2-rc1-alpine3.17
    restart: unless-stopped
    configs:
      - source: redis_config
        target: /usr/local/etc/redis/redis.conf
    networks:
      - ft_trancendence
    expose:
      - "6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3
    entrypoint: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  nginx:
    container_name: nginx_cdn
    image: nginx:alpine3.17
    restart: unless-stopped
    networks:
      - ft_trancendence
    expose:
      - ${CDN_PORT}
    ports:
      - "${CDN_PORT}:${CDN_PORT}"
    environment:
      CDN_PORT: ${CDN_PORT}
      CDN_DOMAIN_NAME: ${CDN_DOMAIN_NAME}
    configs:
      - source: nginx_42trancendence_conf_template
        target: /etc/nginx/templates/42trancendence_cdn.conf.template

  nestjs:
    container_name: backend
    image: 42-ft_transendence-nestjs
    build:
      context: ./backend
    depends_on:
      postgresdb:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - ft_trancendence
    environment:
      REDIS_HOST: ${REDIS_HOST}
      CDN_HOST: ${CDN_HOST}
      CDN_PORT: ${CDN_PORT}


  nextjs:
    container_name: frontend
    image: 42-ft_transendence-nextjs
    build:
      context: ./frontend
    ports:
      - "8080:${NEXT_LISTEN_PORT}"
    depends_on:
      nestjs:
        condition: service_started
    restart: unless-stopped
    networks:
      - ft_trancendence

configs:
  nginx_42trancendence_conf_template:
    file: ./backend/nginx/conf/42trancendence_cdn.conf.template
  postgres_initsql:
    file: ./backend/postgres/conf/init.sh
  redis_config:
    file: ./backend/redis/conf/redis.conf

networks:
  ft_trancendence:
