version: '3.8'

services:
  postgresdb:
    volumes:
      - trancendence_posgresdb:/var/lib/postgresql/data
    # to ensure database is alive before starting every other service
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USER -d $DB_NAME"]
      interval: 10s
      timeout: 5s
      retries: 3
    expose:
      - ${DB_PORT}

  redis:
    volumes:
      - redis_volume:/data

  nginx:
    volumes:
      - cdn_volume:/var/www/42trancendence/avatar:ro

  nestjs:
    expose:
      - ${NEST_LISTEN_PORT}
    volumes:
      - cdn_volume:/trancendence_nestjs/src/avatars
    entrypoint: ["node", "dist/main"]

  nextjs:
    entrypoint: ["npx", "next", "start"]

volumes:
  cdn_volume:
  redis_volume:
  trancendence_posgresdb:
