version: '3.8'

services:
  postgresdb:
    container_name: postgresdb
    image: postgres:14.7-bullseye
    restart: unless-stopped
    configs:
      - source: postgres_initsql
        target: /docker-entrypoint-initdb.d/init.sh
    networks:
      - ft_trancendence

  redis:
    container_name: redis
    image: redis:7.2-rc-bullseye
    restart: unless-stopped
    configs:
      - source: redis_config
        target: /usr/local/etc/redis/redis.conf
    networks:
      - ft_trancendence
    expose:
      - "6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3
    entrypoint: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  nestjs:
    container_name: nestjs
    image: 42-ft_transendence-nestjs
    build:
      context: ./backend
    depends_on:
      postgresdb:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - ft_trancendence

  nextjs:
    container_name: nextjs
    image: 42-ft_transendence-nextjs
    build:
      context: ./frontend
    ports:
      - "3000:${NEXT_LISTEN_PORT}"
    depends_on:
      nestjs:
        condition: service_started
    restart: unless-stopped
    networks:
      - ft_trancendence

configs:
  postgres_initsql:
    file: ./backend/postgres/init.sh
  redis_config:
    file: ./backend/redis/redis.conf

networks:
  ft_trancendence:
