version: '3.8'

services:
  postgresdb:
    container_name: postgresdb
    image: postgres:14.7-bullseye
    restart: unless-stopped
    configs:
      - source: postgres_initsql
        target: /docker-entrypoint-initdb.d/init.sh

  nestjs:
    container_name: nestjs
    build:
      context: ./backend
    depends_on:
      postgresdb:
        condition: service_healthy
    restart: unless-stopped

  nextjs:
    container_name: nextjs
    build:
      context: ./frontend
    ports:
      - "3000:${NEXT_LISTEN_PORT}"
    depends_on:
      postgresdb:
        condition: service_healthy
      nestjs:
        condition: service_started
    restart: unless-stopped

configs:
  postgres_initsql:
    file: ./backend/postgres/init.sh
