#!/bin/bash

psql -U $POSTGRES_USER -c "CREATE DATABASE $DB_NAME;"
psql -U $POSTGRES_USER -c "CREATE USER $DB_USER WITH PASSWORD '$DB_PASSWORD';"
psql -U $POSTGRES_USER -c "GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;"
